### ISSUE TITLE
Very good helper for PHP!

### ISSUE THREAD

**Issue by DINNKA** [WillySleep/CommandHelper#1]
I dont want leave a star at this project. Scam

**Comment by MegaSa1nt** [comment]
cum

**Comment by WillySleep** [comment]
Explain exactly what you don't like and whether you used the project at all. So before you evaluate the project negatively, first try and stay tuned. This project is being updated again and is still relevant. Please, next time, before you criticize, consider your criticism.

**Comment by DINNKA** [comment]
Нифига ты высрал пасту
